import { StyleSheet } from 'react-native';

export const commonOfferStyles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: 40,
    },
    imageContainer: {
        marginBottom: 20,
    },
    image: {
        width: 240,
        height: 240,
    },
    input: {
        width: '80%',
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        marginBottom: 10,
        padding: 10,
    },
    textTitle: {
        width: '80%',
        borderBottomWidth: 2,
        borderBottomColor: '#D0D4CA',
        fontSize: 14,
        paddingTop: 10,
        paddingBottom: 6,
        marginBottom: 10,
    },
    horizontal: {
        width: '80%',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    textPrice: {
        width: '46%',
        height: 40,
        borderBottomWidth: 2,
        borderBottomColor: '#D0D4CA',
        marginBottom: 10,
        paddingBottom: 6,
    },
    textOfferDiscount: {
        width: '48%',
        height: 40,
        borderBottomWidth: 2,
        borderBottomColor: '#D0D4CA',
        marginBottom: 10,
        paddingBottom: 6,
    },
    textRangoOferta: {
        textDecorationLine: 'underline',
        fontWeight: 'bold',
        marginTop: 18,
        fontSize: 14,
        width: '80%',
    },
    textColorBackground: {
        textDecorationLine: 'underline',
        fontWeight: 'bold',
        marginTop: 10,
        fontSize: 14,
        width: '80%',
    },
    touchableContainer: {
        marginTop: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    circularFirst: {
        width: 40,
        height: 40,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    descriptionText: {
        width: '80%',
        fontSize: 14,
        marginTop: 10,
        borderBottomWidth: 2,
        borderBottomColor: '#D0D4CA',
        paddingBottom: 10,
        height: 80,
        justifyContent: "center",
        maxHeight: 200,
    },
    textStarDate: {
        marginTop: 10,
        paddingRight: 40,
        height: 40,
        borderBottomWidth: 2,
        borderBottomColor: '#D0D4CA',
        marginBottom: 10,
        paddingBottom: 6,
    },
    textEndDate: {
        marginTop: 10,
        paddingRight: 40,
        height: 40,
        borderBottomWidth: 2,
        borderBottomColor: '#D0D4CA',
        marginBottom: 10,
        paddingBottom: 6,
    },
    textMonth: {
        fontFamily: 'Roboto',
        fontSize: 14,
        fontWeight: '800',
        height: 'auto',
        paddingBottom: 6,
        textAlignVertical: 'center',
        justifyContent: 'center',
    },
    pickerContainer: {
        marginTop: 14,
        width: '80%',
        borderColor: 'gray',
        borderWidth: 1,
        marginBottom: 10,
    },
    picker: {

    },
    pickerItem: {
        fontSize: 14,
    },
    submitButton: {
        top: 40,
        width: '80%',
        backgroundColor: '#3085C3',
        borderRadius: 10,
        padding: 10,
        marginBottom: 20,
    },

    submitText: {
        color: 'white',
        textAlign: 'center',
        fontSize: 16,
        fontWeight: 'bold',
    },
});
